export { default as Home } from '../Page/Home';
export { default as Task } from '../Page/Task';
export { default as Profile } from './ProfileDashboard';
export { default as Chatbot } from '../Page/Chatbot';
export { default as Setting } from '../Page/Setting';
export { default as  ProfileManagement } from '../Page/ProfileManage'
export { default as Home } from '../Page/Home';
export { default as Task } from '../Page/Task';
export { default as Profile } from './ProfileDashboard';
export { default as Chatbot } from '../Page/Chatbot';
export { default as Setting } from '../Page/Setting';
export { default as  ProfileManagement } from '../Page/ProfileManage'